const chalk = require('chalk')
const pack = require('../package.json')
require('./lib/filters')(hexo)
require('./lib/generators')(hexo)
require('./lib/injector')(hexo)

hexo.on('generateAfter', function () {
  console.log(
    chalk.green('INFO ') +
      chalk.yellow('API data generated by') +
      chalk.cyan.bold(' Aurora v' + pack.version)
  )
})

hexo.on('exit', function () {
  console.log(
    chalk.green('INFO ') + chalk.cyan.bold('Using Aurora v' + pack.version)
  )
})
